### ISSUE TITLE
License

### ISSUE THREAD

**Issue by captainepoch** [daneren2005/ServerProxy#9]
Hi!

I'd like to maintain DSub in a public fork/copy of the repository and your library is needed in order to to it. I also want to make the lib compilable with jitpack.io, and thus, I need to make a fork and change things.

However, not having a license makes imposible to make such changes. 

Would it be possible to add a FLOSS license to the project, please?

Thank you!

**Comment by daneren2005** [comment]
I added the same license that Subsonic uses since that is the main use of it: https://github.com/daneren2005/ServerProxy/blob/master/LICENSE

**Comment by captainepoch** [comment]
Thank you very much!
